version: '3.3'
services:
    mysql-develop:
        build: ./docker/mysql
        container_name: makigumo_mariadb_develop
        restart: always
        command: --log-bin-trust-function-creators=1
        environment:
            MYSQL_DATABASE: makigumo
            MYSQL_USER: makigumo
            MYSQL_PASSWORD: makigumo
            MYSQL_ROOT_PASSWORD: makigumo
        ports:
            - "3306:3306"
        volumes:
            - "./docker/mysql/conf.d/:/etc/mysql/conf.d"
            - "./docker/mysql/log/develop:/var/log/mysql"


